# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port your app runs on (default for Flask is 5000)
EXPOSE 5000

# Define environment variable to avoid Python buffering logs
ENV PYTHONUNBUFFERED=1

# Run the application and bind to 0.0.0.0
CMD ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5000"]
